### ISSUE TITLE
feat: publish as patch bundle

### ISSUE THREAD

**Issue by indrastorms** [zjns/BiliRoamingX-patches#2]
### Feature description

Drop all patches except bilibili and publish as a patch bundle

### Motivation

To use the patches easily alongside official patches
Example : https://github.com/Aunali321/ReVancedExperiments

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by zjns** [comment]
Patcher can recognize whether need patch by package name, so not need drop all patches. And it's convernient to merge upstream.
