### ISSUE TITLE
A small notice

### ISSUE THREAD

**Issue by oSumAtrIX** [zjns/BiliRoamingX-patches#4]
We have a patches project template that can be used to generate a repository:

https://github.com/ReVanced/revanced-patches-template

It is much more specialized for the purpose of creating your own patches and comes with helpful instructions and tips

PS: Soon it will be possible to use multiple patch bundles from any repository at the same time in ReVanced Manager, so you can use your patches side by side with others

**Comment by zjns** [comment]
> PS: Soon it will be possible to use multiple patch bundles from any repository at the same time in ReVanced Manager

Thanks, I am looking forward to it very much.
